/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectoop;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Taufik Yahya
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
        this.setBackground(new java.awt.Color(0,0,0,0));
        jPanel1.setBackground(new java.awt.Color(0,0,0,0));
        txtJeans.setBackground(new java.awt.Color(0,0,0,0));
        txtLs.setBackground(new java.awt.Color(0,0,0,0));
        txtPb.setBackground(new java.awt.Color(0,0,0,0));
        txtShoes.setBackground(new java.awt.Color(0,0,0,0));
        txtSocks.setBackground(new java.awt.Color(0,0,0,0));
        txtTs.setBackground(new java.awt.Color(0,0,0,0));
       
    }
   
    

   
    
    private int insertToTemp(String name, int price, int qty ,Connection conn,Statement s) throws SQLException{
        int sum = price*qty;
        
        try {
        String sql = "INSERT INTO transaction_temp (Date,Name, Price,Qty,Sum) VALUES (?,?,?,?,?)";
        Timestamp date = new Timestamp(new java.util.Date().getTime());
            try (java.sql.PreparedStatement pst = conn.prepareStatement(sql)) {
                pst.setTimestamp(1, date);
                pst.setString(2, name);
                pst.setInt(3, price);
                pst.setInt(4, qty);
                pst.setInt(5, sum);
                pst.execute();
            }
        } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
        }
        return sum;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        txtShoes = new javax.swing.JTextField();
        minShoes = new javax.swing.JButton();
        plusShoes = new javax.swing.JButton();
        txtJeans = new javax.swing.JTextField();
        minJeans = new javax.swing.JButton();
        plusJeans = new javax.swing.JButton();
        txtSocks = new javax.swing.JTextField();
        minSocks = new javax.swing.JButton();
        plusSocks = new javax.swing.JButton();
        txtPb = new javax.swing.JTextField();
        minPb = new javax.swing.JButton();
        plusPb = new javax.swing.JButton();
        txtTs = new javax.swing.JTextField();
        minTs = new javax.swing.JButton();
        plusTs = new javax.swing.JButton();
        txtLs = new javax.swing.JTextField();
        minLs = new javax.swing.JButton();
        plusLs = new javax.swing.JButton();
        Menu = new javax.swing.JButton();
        btnCart = new javax.swing.JButton();
        menu = new javax.swing.JLabel();

        jMenuItem1.setText("aaaaaa");
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(780, 692));

        jPanel1.setPreferredSize(new java.awt.Dimension(759, 665));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtShoes.setEditable(false);
        txtShoes.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtShoes.setForeground(new java.awt.Color(245, 247, 250));
        txtShoes.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtShoes.setText("0");
        txtShoes.setBorder(null);
        txtShoes.setOpaque(false);
        jPanel1.add(txtShoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 20, 30));

        minShoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minShoes.setBorder(null);
        minShoes.setBorderPainted(false);
        minShoes.setContentAreaFilled(false);
        minShoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minShoesActionPerformed(evt);
            }
        });
        jPanel1.add(minShoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        plusShoes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusShoes.setBorder(null);
        plusShoes.setBorderPainted(false);
        plusShoes.setContentAreaFilled(false);
        plusShoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusShoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusShoesActionPerformed(evt);
            }
        });
        jPanel1.add(plusShoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, -1));

        txtJeans.setEditable(false);
        txtJeans.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtJeans.setForeground(new java.awt.Color(245, 247, 250));
        txtJeans.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtJeans.setText("0");
        txtJeans.setBorder(null);
        txtJeans.setOpaque(false);
        jPanel1.add(txtJeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 20, 30));

        minJeans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minJeans.setBorder(null);
        minJeans.setBorderPainted(false);
        minJeans.setContentAreaFilled(false);
        minJeans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minJeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minJeansActionPerformed(evt);
            }
        });
        jPanel1.add(minJeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        plusJeans.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusJeans.setBorder(null);
        plusJeans.setBorderPainted(false);
        plusJeans.setContentAreaFilled(false);
        plusJeans.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusJeans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusJeansActionPerformed(evt);
            }
        });
        jPanel1.add(plusJeans, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, -1, -1));

        txtSocks.setEditable(false);
        txtSocks.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtSocks.setForeground(new java.awt.Color(245, 247, 250));
        txtSocks.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSocks.setText("0");
        txtSocks.setBorder(null);
        txtSocks.setOpaque(false);
        jPanel1.add(txtSocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 20, 30));

        minSocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minSocks.setBorder(null);
        minSocks.setBorderPainted(false);
        minSocks.setContentAreaFilled(false);
        minSocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minSocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minSocksActionPerformed(evt);
            }
        });
        jPanel1.add(minSocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        plusSocks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusSocks.setBorder(null);
        plusSocks.setBorderPainted(false);
        plusSocks.setContentAreaFilled(false);
        plusSocks.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusSocks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusSocksActionPerformed(evt);
            }
        });
        jPanel1.add(plusSocks, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, -1, -1));

        txtPb.setEditable(false);
        txtPb.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtPb.setForeground(new java.awt.Color(245, 247, 250));
        txtPb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPb.setText("0");
        txtPb.setBorder(null);
        txtPb.setOpaque(false);
        jPanel1.add(txtPb, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 20, 30));

        minPb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minPb.setBorder(null);
        minPb.setBorderPainted(false);
        minPb.setContentAreaFilled(false);
        minPb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minPb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minPbActionPerformed(evt);
            }
        });
        jPanel1.add(minPb, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 540, -1, -1));

        plusPb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusPb.setBorder(null);
        plusPb.setBorderPainted(false);
        plusPb.setContentAreaFilled(false);
        plusPb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusPb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusPbActionPerformed(evt);
            }
        });
        jPanel1.add(plusPb, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, -1, -1));

        txtTs.setEditable(false);
        txtTs.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtTs.setForeground(new java.awt.Color(245, 247, 250));
        txtTs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtTs.setText("0");
        txtTs.setBorder(null);
        txtTs.setOpaque(false);
        jPanel1.add(txtTs, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 20, 30));

        minTs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minTs.setBorder(null);
        minTs.setBorderPainted(false);
        minTs.setContentAreaFilled(false);
        minTs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minTs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minTsActionPerformed(evt);
            }
        });
        jPanel1.add(minTs, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 540, -1, -1));

        plusTs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusTs.setBorder(null);
        plusTs.setBorderPainted(false);
        plusTs.setContentAreaFilled(false);
        plusTs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusTs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusTsActionPerformed(evt);
            }
        });
        jPanel1.add(plusTs, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        txtLs.setEditable(false);
        txtLs.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        txtLs.setForeground(new java.awt.Color(245, 247, 250));
        txtLs.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLs.setText("0");
        txtLs.setBorder(null);
        txtLs.setOpaque(false);
        jPanel1.add(txtLs, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 540, 20, 30));

        minLs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/-.png"))); // NOI18N
        minLs.setBorder(null);
        minLs.setBorderPainted(false);
        minLs.setContentAreaFilled(false);
        minLs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minLs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minLsActionPerformed(evt);
            }
        });
        jPanel1.add(minLs, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 540, -1, -1));

        plusLs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/+.png"))); // NOI18N
        plusLs.setBorder(null);
        plusLs.setBorderPainted(false);
        plusLs.setContentAreaFilled(false);
        plusLs.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusLs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusLsActionPerformed(evt);
            }
        });
        jPanel1.add(plusLs, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 540, -1, -1));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Menu Button.png"))); // NOI18N
        Menu.setBorder(null);
        Menu.setBorderPainted(false);
        Menu.setComponentPopupMenu(jPopupMenu1);
        Menu.setContentAreaFilled(false);
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.setFocusPainted(false);
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });
        jPanel1.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, -1, -1));

        btnCart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Checkout.png"))); // NOI18N
        btnCart.setBorder(null);
        btnCart.setBorderPainted(false);
        btnCart.setContentAreaFilled(false);
        btnCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCart.setFocusPainted(false);
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });
        jPanel1.add(btnCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 590, -1, -1));

        menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Main Program.png"))); // NOI18N
        jPanel1.add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 770, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void minShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minShoesActionPerformed
        // TODO add your handling code here:
        String strVa = txtShoes.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtShoes.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minShoesActionPerformed

    private void plusShoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusShoesActionPerformed
        // TODO add your handling code here:
        String strVa = txtShoes.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtShoes.setText(result);
    }//GEN-LAST:event_plusShoesActionPerformed

    private void minJeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minJeansActionPerformed
        // TODO add your handling code here:
        String strVa = txtJeans.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtJeans.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minJeansActionPerformed

    private void plusJeansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusJeansActionPerformed
        // TODO add your handling code here:
        String strVa = txtJeans.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtJeans.setText(result);
    }//GEN-LAST:event_plusJeansActionPerformed

    private void minSocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minSocksActionPerformed
        // TODO add your handling code here:
        String strVa = txtSocks.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtSocks.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minSocksActionPerformed

    private void plusSocksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusSocksActionPerformed
        // TODO add your handling code here:
         String strVa = txtSocks.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtSocks.setText(result);
    }//GEN-LAST:event_plusSocksActionPerformed

    private void minPbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minPbActionPerformed
        // TODO add your handling code here:
        String strVa = txtPb.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtPb.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minPbActionPerformed

    private void plusPbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusPbActionPerformed
        // TODO add your handling code here:
        String strVa = txtPb.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtPb.setText(result);
    }//GEN-LAST:event_plusPbActionPerformed

    private void minTsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minTsActionPerformed
        // TODO add your handling code here:
        String strVa = txtTs.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtTs.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minTsActionPerformed

    private void plusTsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusTsActionPerformed
        // TODO add your handling code here:
        String strVa = txtPb.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtTs.setText(result);
    }//GEN-LAST:event_plusTsActionPerformed

    private void minLsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minLsActionPerformed
        // TODO add your handling code here:
        String strVa = txtLs.getText();
        int value = Integer.parseInt(strVa);
        if (value > 0) {            
        value --;
        String result = String.valueOf(value);
        txtLs.setText(result);
        }else{
            JOptionPane.showMessageDialog(this, "Can't be less then zero" );
        }
    }//GEN-LAST:event_minLsActionPerformed

    private void plusLsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusLsActionPerformed
        // TODO add your handling code here:
        String strVa = txtLs.getText();
        int value = Integer.parseInt(strVa);
        value ++;
        String result = String.valueOf(value);
        txtLs.setText(result);
    }//GEN-LAST:event_plusLsActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
        Option newOpt = new Option();
        newOpt.setVisible(true);
    }//GEN-LAST:event_MenuActionPerformed

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
        try {                                        
            // Nilai Item
            String strVaS = txtShoes.getText();
            int valueS = Integer.parseInt(strVaS);
            String strVaJ = txtJeans.getText();
            int valueJ = Integer.parseInt(strVaJ);
            String strVaSo = txtSocks.getText();
            int valueSo = Integer.parseInt(strVaSo);
            String strVaP = txtPb.getText();
            int valueP = Integer.parseInt(strVaP);
            String strVaT = txtTs.getText();
            int valueT = Integer.parseInt(strVaT);
            String strVaL = txtLs.getText();
            int valueL = Integer.parseInt(strVaL);
            
            //Harga Item
            int priceShoes = 350000;
            int priceSocks = 50000;
            int priceJeans = 150000;
            int pricePb = 60000;
            int priceTs = 120000;
            int priceLs = 145000;
            
            
            int localTotal = 0;
            
            
            
            if (valueJ>0||valueL>0||valueP>0||valueS>0||valueSo>0||valueT>0) {
                Connection conn = (Connection)finalprojectoop.connect.getConnection();
                Statement s = conn.createStatement();
                //Sepatu
                if(valueS>0){
                    String name = "Red Shoes";
                    int x =insertToTemp(name, priceShoes, valueS,conn,s);
                    localTotal += x;
                }
                //Blue Jeans
                if(valueJ>0){
                    String name = "Blue Jeans";
                    int x =insertToTemp(name, priceJeans, valueJ ,conn,s);
                     localTotal += x;
                }

                //Blue socks
                if(valueSo>0){
                    String name = "Blue Socks";
                    int x =insertToTemp(name, priceSocks, valueSo ,conn,s);
                     localTotal += x;
                }
                //Pouch Bag
                if(valueP>0){
                    String name = "Pouch Bag";
                    int x =insertToTemp(name, pricePb, valueP ,conn,s);
                     localTotal += x;
                }
                //Black TS
                if(valueT>0){
                    String name = "Black T-shirt";
                    int x =insertToTemp(name, priceTs, valueT ,conn,s);
                     localTotal += x;
                }
                //LS
                if(valueL>0){
                    String name = "Long Shirt";
                    int x =insertToTemp(name, priceLs, valueL ,conn,s);
                     localTotal += x;
                }
                System.out.println(localTotal);
                String x = String.valueOf(localTotal);
                TransactionDetails newDetails = new TransactionDetails();
                TransactionDetails.txtTotal.setText(x);
                newDetails.setVisible(true);
                this.dispose();   
            }else{
                JOptionPane.showMessageDialog(this, "You haven't buy anyone yet" );
            }
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>       

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JButton btnCart;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel menu;
    private javax.swing.JButton minJeans;
    private javax.swing.JButton minLs;
    private javax.swing.JButton minPb;
    private javax.swing.JButton minShoes;
    private javax.swing.JButton minSocks;
    private javax.swing.JButton minTs;
    private javax.swing.JButton plusJeans;
    private javax.swing.JButton plusLs;
    private javax.swing.JButton plusPb;
    private javax.swing.JButton plusShoes;
    private javax.swing.JButton plusSocks;
    private javax.swing.JButton plusTs;
    private javax.swing.JTextField txtJeans;
    private javax.swing.JTextField txtLs;
    private javax.swing.JTextField txtPb;
    private javax.swing.JTextField txtShoes;
    private javax.swing.JTextField txtSocks;
    private javax.swing.JTextField txtTs;
    // End of variables declaration//GEN-END:variables
}
