/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalprojectoop;

import java.awt.MouseInfo;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Dirga Astya W
 */
public class Option extends javax.swing.JFrame {

    /**
     * Creates new form Option
     */
    public Option() {
        initComponents();
        this.setBackground(new java.awt.Color(0,0,0,0));
        int mposX = MouseInfo.getPointerInfo().getLocation().x;
        int mposY = MouseInfo.getPointerInfo().getLocation().y;
        setLocation(900,101);
        System.out.println(mposX);
        System.out.println(mposY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logut = new javax.swing.JButton();
        Report = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Logout Button.png"))); // NOI18N
        Logut.setBorder(null);
        Logut.setBorderPainted(false);
        Logut.setContentAreaFilled(false);
        Logut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Logut.setFocusPainted(false);
        Logut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogutActionPerformed(evt);
            }
        });
        getContentPane().add(Logut, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 110, -1));

        Report.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Report Button.png"))); // NOI18N
        Report.setBorder(null);
        Report.setBorderPainted(false);
        Report.setContentAreaFilled(false);
        Report.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Report.setFocusPainted(false);
        Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportActionPerformed(evt);
            }
        });
        getContentPane().add(Report, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Back Button.png"))); // NOI18N
        Back.setBorder(null);
        Back.setBorderPainted(false);
        Back.setContentAreaFilled(false);
        Back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Back.setFocusPainted(false);
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Popup.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportActionPerformed
        try {
            // TODO add your handling code here:
            Home newHome = new Home();
            newHome.dispose();
            newHome.setVisible(false);
            this.dispose();
            Report newReport = new Report();
            newReport.setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Option.class.getName()).log(Level.SEVERE, null, ex);
        }
        

    }//GEN-LAST:event_ReportActionPerformed

    private void LogutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogutActionPerformed
        try {
            // TODO add your handling code here:
            Home newHome = new Home();
            newHome.dispose();
            newHome.setVisible(false);
            Login newLogin = new Login();
            newLogin.setVisible(true);
            this.dispose();
            
        } catch (SQLException ex) {
            Logger.getLogger(Option.class.getName()).log(Level.SEVERE, null, ex);
        }
        try ( // TODO add your handling code here:
                Connection conn = (Connection)finalprojectoop.connect.getConnection()) {
                Statement s = conn.createStatement();
                
                String sql = "DELETE FROM transaction_temp";
                s = conn.createStatement();
                s.executeUpdate(sql);
                conn.close();
            } catch (SQLException ex) {
            Logger.getLogger(Option.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_LogutActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        // TODO add your handling code here:
       
        Option.this.setVisible(false);
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Option.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Option().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton Logut;
    private javax.swing.JButton Report;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
